CREATE TABLE IF NOT EXISTS users(
	id UUID NOT NULL PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	email VARCHAR(60) NOT NULL,
	password TEXT NOT NULL,
	currency_id UUID NOT NULL
);

CREATE TABLE IF NOT EXISTS roles(
	id UUID NOT NULL PRIMARY KEY,
	name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS user_role(
	user_id UUID NOT NULL,
	role_id UUID NOT NULL,
	PRIMARY KEY (user_id, role_id),
	CONSTRAINT fk_user_id
		FOREIGN KEY (user_id)
		REFERENCES users(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	CONSTRAINT fk_role_id
		FOREIGN KEY (role_id)
		REFERENCES roles(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);
