apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: devops-labs
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-labs
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: devops-labs
        tier: database
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: postgres-password
          volumeMounts:
            - name: postgres-volume-mount
              mountPath: /var/lib/postgresql/data
              subPath: postgres
            - name: init-db
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
      volumes:
        - name: postgres-volume-mount
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: init-db
          configMap:
            name: postgres-init-config